stages:
  - build

variables:
  # Set CICD variables in gitlab project first: 
  # DOCKER_SERVER / DOCKER_REPO / DOCKER_USERNAME / DOCKER_PASSWORD
  DOCKER_IMAGE_NAME: $DOCKER_SERVER/$DOCKER_REPO
  DEFAULT_TAG: $CI_COMMIT_SHORT_SHA

build-and-push:
  stage: build
  tags:
    - global-runner
  script:
    - echo "Building Docker image..."
    
    # Login to Docker Hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" $DOCKER_SERVER --password-stdin
    
    # Check if IMAGE_TAG variable is set. If not, use DEFAULT_TAG as the image tag.
    - if [ -z "$IMAGE_TAG" ]; then export IMAGE_TAG=$DEFAULT_TAG; else export IMAGE_TAG=$IMAGE_TAG; fi
    - echo "$DOCKER_IMAGE_NAME:$IMAGE_TAG"
    
    # Build and push Docker image
    - pwd && ls -l
    # - docker build -t $DOCKER_IMAGE_NAME:$IMAGE_TAG $CI_PROJECT_DIR
    - > 
      docker build --network=host  
      --build-arg HTTP_PROXY=http://192.168.50.200:10809   
      --build-arg HTTPS_PROXY=http://192.168.50.200:10809 
      -t $DOCKER_IMAGE_NAME:$IMAGE_TAG .
    - docker push $DOCKER_IMAGE_NAME:$IMAGE_TAG
    # Logout from Docker Hub
    - docker logout $DOCKER_SERVER
  when: manual
  only:
    - main