apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  # labels:
  #  run: podtemplate
  # annotations:
  #  run: podtemplate
  name: podtemplate
spec:
  containers:
  - image: voidking/debian:bookworm-slim-curl
    name: debian
    resources: 
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: '1'
        memory: 512Mi
    command: ["/bin/sh", "-c"]
    args:
    - tail -f /dev/null
    env:
    - name: ENV
      value: test
    - name: ENV3
      value: test
status: {}