apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podtemplate
  name: podtemplate
spec:
  containers:
  - image: voidking/debian:bookworm-slim-curl
    name: debian
    resources: {}
    command: ["/bin/sh", "-c"]
    args:
    - tail -f /dev/null
    env:
    - name: ENV
      value: test
    - name: ENV3
      value: test
status: {}