apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webhook
  name: webhook
  namespace: k8s-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webhook
    spec:
      containers:
      - name: k8s-webhook
        image: voidking/k8s-webhook:v0.1.1
        envFrom:
        - configMapRef:
            name: webhook-env
        resources: {}
        volumeMounts:
        - name: config
          mountPath: "/etc/k8s-webhook/configs"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: webhook-config
          # 来自 ConfigMap 的一组键，将被创建为文件
          items:
          - key: "config.yaml"
            path: "config.yaml"
          - key: "podtemplate.yaml"
            path: "podtemplate.yaml"
status: {}
