apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webhook
  name: webhook
  namespace: k8s-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webhook
    spec:
      serviceAccountName: webhook
      containers:
      - name: k8s-webhook
        image: voidking/k8s-webhook:v0.0.1
        envFrom:
        - configMapRef:
            name: webhook-env
        resources: {}
status: {}
