apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: k8s-webhook
webhooks:
- name: webhook.k8s-webhook.svc
  clientConfig:
    # url适用于apiserver访问集群外的webhook，service适用于apiserver访问集群内webhook
    #url: "https://webhook.k8s-webhook.svc/pod/mutating"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVlVENDQXVHZ0F3SUJBZ0lRQ3QyaEdsTzNwdUx2K3lGYUI0UzRqVEFOQmdrcWhraUc5dzBCQVFzRkFEQlYKTVI0d0hBWURWUVFLRXhWdGEyTmxjblFnWkdWMlpXeHZjRzFsYm5RZ1EwRXhGVEFUQmdOVkJBc01ESEp2YjNSQQpiRzlqWVd4allURWNNQm9HQTFVRUF3d1RiV3RqWlhKMElISnZiM1JBYkc5allXeGpZVEFlRncweU5ERXdNRGd3Ck56TXpOVFZhRncwek5ERXdNRGd3TnpNek5UVmFNRlV4SGpBY0JnTlZCQW9URlcxclkyVnlkQ0JrWlhabGJHOXcKYldWdWRDQkRRVEVWTUJNR0ExVUVDd3dNY205dmRFQnNiMk5oYkdOaE1Sd3dHZ1lEVlFRRERCTnRhMk5sY25RZwpjbTl2ZEVCc2IyTmhiR05oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUFzZkM2Cit5QWsxS3pqalFHZnFETHc5NUREdUxZSUM2djNWVDdJclkxSjRiTTZKZUFTaHJlcUg2QitTNGVNaHBLQ3FzQ0QKSGVDdUM4MGhjaXRoMHNTUUEzeUFWYUlHWm5pTDdzbEM5SHV2RGRTdFpudjdzRnNNTzY3cE5CU1IxTU9JVzRGRApsWm5oZ2pCNy91VzBQNmVlUmhuRVBFU0NDWW5MeThmaWF5U3djZjFQV1R3Y05WeW5hTmVQZmtzK1Q1aVJsWHM0CjVXMWRudVZmK1JyMEtma3VnMGVYWE82WHJ4VWx2TlFhQzdFVDR1V3VXMTJRMFVuaExKeXdvV3U1dzJTWVJ4Z2YKK1pkQ3F6UDlObTI0WDluMFlVZTZlZDNGU2NIbkpCWWdSWkVRbE9qN0ptakh2Y05RNlJ0SVZObUVFQmQzYU1ncgo3Um1qWlNhcndQV3ZpYy9oemVMUzR5bXJnZHVpendTUHhvc1pXcjRYMnAyU0FjMVdlNG5kZ3VCTnhsYmFhV1FiCjhhTXR0dExQK0tPY1pCZ082d1QzR1NCbzg5SlN6cnNudmpvYjhvVzVlUUdrL2lWcHhkWldIczRTV1BoRFZ6UXoKeURVdGRUakx2SHhqSzl2dU5RcGIwRnNuaUVQc2h0VlA4K29ZNEhYTlA3QkNDWGNkeVJMMXo0NGlPSDN4QWdNQgpBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUVBd0lDQkRBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQU1CMEdBMVVkCkRnUVdCQlRDeExUbFA5ZVc4VUpDakp4akVMU3JJQ094c1RBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVlFQUNQWGgKYVFINVZEVkxpbVhLSnFCYXd5blB0eVRrQW1OckY3UCtTRGZnbkRsR05pMW1PRStZdzZjVWJhKzh0bmhzZytVegpreWRJZkp2MUJpdlJMUFI0ZEg4QzJCSHY4ZDIzMkJ6dkNGYlN6NFUxSXFlSmJJMzE0RFFINnlaV1V0a1hxYzlzCi9ta3RDMmNraDdYQldHMFdyeVZidEVrMnNlbXRTNEw4TUs2UWI5WElYMWp6ejVmUlJWQkorV1k0NEdMSTNDTGcKcXVZNk5pcjVudE8wY1RKOWRTY0IvZGhVajlUSVRzSGtOMmROUzcwOHNPYTdJZnFOT05QMXcwZ2lQOTBzSDFDSwpTY3JZOWsrVEtEWUdtUEZBM1JNbm84SWIxTFN2bXJnLzQ5QWt6cEtITENYVUsvT05zcTFHWXIvOEx5ZmVHQ28yCkhIYVByNStPSSt4enZsU0ZFYVJPb2NJdFprN2xoM0VLWUoyTGhMNjR4K2p6UTFZblpybm8vV2VXSGRNT3l2WEUKQ1liR2lXRlNFY3pIckljYTcxVVNISUJ1UDF4VlJpa3A3TDRXMGMzVWpkWXNaV2MyRGxEbkM4UVVLTW5mYnhGKwpMMmY5dllmeWVnR0xCMmxHSU5tWkduMEllUGk5cy94d2h4WVpObWw0Wnp4Q2FlM3ZYOGhQZFFOaGhnV2YKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
        name: webhook
        namespace: k8s-webhook
        port: 8443
        path: /pod/mutating
  objectSelector:
    matchExpressions:
    - key: "webhook"
      operator: "Exists"
    # - key: "app"
    #   operator: "In"
    #   values: ["myapp"]
  rules:
  - operations: ["CREATE","UPDATE"]
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["pods"]
    scope: "*"
  failurePolicy: Fail
  sideEffects: None
  admissionReviewVersions: ["v1"]