name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Image Tag (optional)'
        required: false
        default: ''
# https://docs.github.com/en/actions/learn-github-actions/variables
# https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions
# There are 3 methods to set variables in github actions: vars, secrets, env
# Set variables in github project: DOCKER_SERVER / DOCKER_REPO / DOCKER_USERNAME 
# Set secrets in github project: DOCKER_PASSWORD / FEISHU_WEBHOOK_URL
# env: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    # Define a step to set the commit SHA environment variable if the tag is not provided
    - name: Get short SHA
      id: sha
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

    - name: Define the Docker image name to env
      run: echo "DOCKER_IMAGE_NAME=${{ vars.DOCKER_SERVER }}/${{ vars.DOCKER_REPO }}" >> $GITHUB_ENV
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.DOCKER_SERVER }}
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.tag || steps.sha.outputs.sha }}

    - name: Logout from Docker Hub
      run: |
        echo "${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.tag || steps.sha.outputs.sha }}"
        docker logout ${{ vars.DOCKER_SERVER }}
    
    - name: Send notification to FeiShu
      run: >
        curl -X POST -H "Content-Type: application/json" --data "{
          \"msg_type\": \"text\",
          \"content\": {
            \"text\": \"Docker image ${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.tag || steps.sha.outputs.sha }} is built and pushed successfully.\"
          }
        }" ${{ secrets.FEISHU_WEBHOOK_URL }}